### PR TITLE
Added invest costs for car, some bug fixing

### PR DESCRIPTION
**Pull request by thmichel**

### CODE REVIEW

**Comment by condo4** [comment]
I have a problem to validate the application with Sailfish QA :

Thank you for submitting your application CarBudget to our Harbour. However, I am sorry to inform that I am not yet able to accept the changes you have made. RPM validator is giving the following error message: 

ERROR [/usr/share/harbour-carbudget/qml/pages/SelectImportFile.qml] Import 'Qt.labs.folderlistmodel 2.1' is not allowed
So, you are using some QLM imports, which are not allowed, for instructions, see:
https://harbour.jolla.com/faq#QML_API Also, here is information of how you can validate your RPM with SailfishSDK: https://harbour.jolla.com/faq#9.1.0.

Another thing related to this information import. I was not able to make the import working (this might be due to this error message that the rpm validator is giving). And because of that, I wasn’t able finish our QA testing practises. I will attach here some screen-shots, and you can verify that I'm using the right MyCar application. I am also providing a shot of the import log. See those screen-shots here: https://app.younited.com/?shareObject=52c51e13-c95e-0281-1a66-84900daa9448

Thank you for your understanding! I hope you find this message helpful and if you have any questions, don't hesitate to contact developer-care@jolla.com.

Best regards,
Jenni

**Comment by thmichel** [comment]
Hi,

that's very strange as there have been no changes to the import function
recently, we always used folderlistmodel (and it worked without problems).

However, I checked the list of allowed imports and it is not there. I have
no idea at the moment how to change it as there is no other API for file
opening that I am aware of. Maybe I need to code this entirely new in C++
:-(

As for the tires, I have not yet coded anything as I was quite busy last
days, but I have a basic idea: What about using tires and tire sets, so
that multiple tires form a tire set? This way it would be possible to
replace single tires within a set.

Regards,

Tom.

Zitat von Proriol Fabien <notifications@github.com>:

> I have a problem to validate the application with Sailfish QA :
>
>   Thank you for submitting your application CarBudget to our Harbour.
> However, I am sorry to inform that I am not yet able to accept the
> changes you have made. RPM validator is giving the following error
> message:
>
>   ERROR [/usr/share/harbour-carbudget/qml/pages/SelectImportFile.qml]
> Import 'Qt.labs.folderlistmodel 2.1' is not allowed
> So, you are using some QLM imports, which are not allowed, for
> instructions, see:
> https://harbour.jolla.com/faq#QML_API Also, here is information of how
> you can validate your RPM with SailfishSDK:
> https://harbour.jolla.com/faq#9.1.0.
>
>   Another thing related to this information import. I was not able to
> make the import working (this might be due to this error message that
> the rpm validator is giving). And because of that, I wasn’t able finish
> our QA testing practises. I will attach here some screen-shots, and you
> can verify that I'm using the right MyCar application. I am also
> providing a shot of the import log. See those screen-shots here:
>
https://app.younited.com/?shareObject=52c51e13-c95e-0281-1a66-84900daa9448
>
>   Thank you for your understanding! I hope you find this message helpful
> and if you have any questions, don't hesitate to contact
> developer-care@jolla.com.
>
>   Best regards,
> Jenni
>
>   —
> Reply to this email directly or view it on GitHub[1].
>       



Links:
------
[1] https://github.com/condo4/carbudget/pull/18#issuecomment-110746007

**Comment by condo4** [comment]
Hello,

The application is still reject by QA, I need to work on some bugs in new features like cost type...
I copy all reported issue by QA in github issue.
I can reproduce some of them, but not all...
I will work on it, probably this week

Regards,
Fabien

**Comment by thmichel** [comment]
Hi,

thanks for the information.

I looked at github, I could work on the following:
- Import from mycar: I could create a help page that is available in the
import menu
- Not Set types: I think it makes sense to disable the Context Menu for
this in all dialogs for all types (stations, cost types) as they are not
stored in the database but added as default option in the Lists
- Missing Cost Types: I think I've seen that somewher and did already some
fix to that in the tire experimental branch.

As for the crash and data loss I have no idea yet.

Regards,

Tom.

Zitat von Proriol Fabien <notifications@github.com>:

> Hello,
>
>   The application is still reject by QA, I need to work on some bugs in
> new features like cost type...
> I copy all reported issue by QA in github issue.
> I can reproduce some of them, but not all...
> I will work on it, probably this week
>
>   Regards,
> Fabien
>
>   —
> Reply to this email directly or view it on GitHub[1].
>       



Links:
------
[1] https://github.com/condo4/carbudget/pull/18#issuecomment-125135253

**Comment by thmichel** [comment]
Hi Fabien,

is there anything I can help with fixing to get the updat to harbour? I
gues the last version there is quite old?

Regards,

Tom.

Zitat von Proriol Fabien <notifications@github.com>:

> Hello,
>
>   The application is still reject by QA, I need to work on some bugs in
> new features like cost type...
> I copy all reported issue by QA in github issue.
> I can reproduce some of them, but not all...
> I will work on it, probably this week
>
>   Regards,
> Fabien
>
>   —
> Reply to this email directly or view it on GitHub[1].
>       



Links:
------
[1] https://github.com/condo4/carbudget/pull/18#issuecomment-125135253

**Comment by condo4** [comment]
Hi,

I think the last think is missing is to fix:
https://github.com/condo4/carbudget/issues/24 (I did a fix, but it can 
fix only a part of data lose, not all...)

But, I can't reproduce this bug...
Perhaps, I can retry a QA validation to see if it's accepted in the 
current state.

In this moment, I'm working more on QML2048 in order to can use screen 
orientation for the tablet, and I will porte this 2 apps for tablet.

But you are right, current version on harbour is very old, and it's 
important to valid all current change before...


Fabien

**Pull request merged**
