### PR TITLE
Added cost types and fuel types, created import utility for Android myCar app

### PR DESCRIPTION
**Pull request by thmichel**
Import feature added to import xml backup from android app myCar.
xml file must be placed into /home/nemo/
To add myCar records, cost types (e.g. Repair, Insurance,..) have been added as wall as fuel types (Diesel, E10 etc).

Might be usefull for users migrating from Android to Jolla (like me :-) )

### CODE REVIEW

**Comment by condo4** [comment]
I rewrite your patch, because, there is some bug when I test all features, it was missing simulation (I use this to check if all is working well), and I need to separate this 3 features:
- FuelType
- CostType
- Import
Today, I merged FuelType and CostType, but I need to work a lot for Import...
In fact, in my apps, I really need a distance for cost, because I will use it to do some statistics.
In your case, I think the good way is to calculate by a lineare interpolation the distance with fuel tanks information.
Exemple:
Fuel: 2014-01-01 at 1000 km
Fuel: 2014-01-11 at 2000 km

If new cost import at 2014-01-06, we can use 1500km as distance.
If new cost is newer than all fuel, we can take the last distance information.

I will commit this release today (and generate a new version), and probably work on this feature tomorrow... to generate it next week.

Another feature I want to do is to sort station and fueltype by usage, ie by total quantity of fuel use by this type or station...

**Comment by thmichel** [comment]
Hi,

that's great.

I already found some bugs in the code I worte and did some more changes
(mainly to the statistics and some gui modifications)

I'll merge your changes into mine and send another pull request later on.

Regarding the simulations: I was just too lazy to rewrite all the
statements :-) I have an xml Export from myCar with about 100 fuel records
and some 20 costs that I use for testing...

Thanks for merging my changes!

Zitat von Proriol Fabien <notifications@github.com>:

> I rewrite your patch, because, there is some bug when I test all
> features, it was missing simulation (I use this to check if all is
> working well), and I need to separate this 3 features:
>
>
>   *    FuelType
>   *    CostType
>   *    Import Today, I merged FuelType and CostType, but I need to work
> a lot for Import... In fact, in my apps, I really need a distance for
> cost, because I will use it to do some statistics. In your case, I think
> the good way is to calculate by a lineare interpolation the distance
> with fuel tanks information. Exemple: Fuel: 2014-01-01 at 1000 km Fuel:
> 2014-01-11 at 2000 km
>
>   If new cost import at 2014-01-06, we can use 1500km as distance.
> If new cost is newer than all fuel, we can take the last distance
> information.
>
>   I will commit this release today (and generate a new version), and
> probably work on this feature tomorrow... to generate it next week.
>
>   Another feature I want to do is to sort station and fueltype by usage,
> ie by total quantity of fuel use by this type or station...
>
>   —
> Reply to this email directly or view it on GitHub[1].
>       



Links:
------
[1] https://github.com/condo4/carbudget/pull/10#issuecomment-83613984

**Comment by condo4** [comment]
Hi, 

I think also it will be greate to select the xml file from a list
instead of a hard coded name, for exemple, we can propose all ~/*.xml
and ~/Documents/*.xml 

I want to write also the import from the old N900 application I used,
but, at this time, I hadn't the time to do it... 

Fabien 

> Hi,
> 
> that's great.
> 
> I already found some bugs in the code I worte and did some more changes
> (mainly to the statistics and some gui modifications)
> 
> I'll merge your changes into mine and send another pull request later on.
> 
> Regarding the simulations: I was just too lazy to rewrite all the
> statements :-) I have an xml Export from myCar with about 100 fuel records
> and some 20 costs that I use for testing...
> 
> Thanks for merging my changes!
> 
> Zitat von Proriol Fabien <notifications@github.com>:
> 
>> I rewrite your patch, because, there is some bug when I test all
>> features, it was missing simulation (I use this to check if all is
>> working well), and I need to separate this 3 features:
>>
>>
>> * FuelType
>> * CostType
>> * Import Today, I merged FuelType and CostType, but I need to work
>> a lot for Import... In fact, in my apps, I really need a distance for
>> cost, because I will use it to do some statistics. In your case, I think
>> the good way is to calculate by a lineare interpolation the distance
>> with fuel tanks information. Exemple: Fuel: 2014-01-01 at 1000 km Fuel:
>> 2014-01-11 at 2000 km
>>
>> If new cost import at 2014-01-06, we can use 1500km as distance.
>> If new cost is newer than all fuel, we can take the last distance
>> information.
>>
>> I will commit this release today (and generate a new version), and
>> probably work on this feature tomorrow... to generate it next week.
>>
>> Another feature I want to do is to sort station and fueltype by usage,
>> ie by total quantity of fuel use by this type or station...
>>
>> --
>> Reply to this email directly or view it on GitHub[1].
>> 
> 
> Links:
> ------
> [1] https://github.com/condo4/carbudget/pull/10#issuecomment-83613984 
> 
> --
> Reply to this email directly or view it on GitHub [1].

 

Links:
------
[1] https://github.com/condo4/carbudget/pull/10#issuecomment-83615645

**Comment by thmichel** [comment]
Hi Fabien,

good Idea, just had not yet the time to find out how to do that :-)

Couldn't find a default fileopen dialog, need to look into that.

Regards,

Tom.
Zitat von Proriol Fabien <notifications@github.com>:

> Hi,
>
> I think also it will be greate to select the xml file from a list
> instead of a hard coded name, for exemple, we can propose all ~/*.xml
> and ~/Documents/*.xml
>
> I want to write also the import from the old N900 application I used,
> but, at this time, I hadn't the time to do it...
>
> Fabien
>
>> Hi,
>>
>> that's great.
>>
>> I already found some bugs in the code I worte and did some more changes
>> (mainly to the statistics and some gui modifications)
>>
>> I'll merge your changes into mine and send another pull request later
on.
>>
>> Regarding the simulations: I was just too lazy to rewrite all the
>> statements :-) I have an xml Export from myCar with about 100 fuel
>> records
>> and some 20 costs that I use for testing...
>>
>> Thanks for merging my changes!
>>
>> Zitat von Proriol Fabien <notifications@github.com>:
>>
>>> I rewrite your patch, because, there is some bug when I test all
>>> features, it was missing simulation (I use this to check if all is
>>> working well), and I need to separate this 3 features:
>>>
>>>
>>> * FuelType
>>> * CostType
>>> * Import Today, I merged FuelType and CostType, but I need to work
>>> a lot for Import... In fact, in my apps, I really need a distance for
>>> cost, because I will use it to do some statistics. In your case, I
think
>>> the good way is to calculate by a lineare interpolation the distance
>>> with fuel tanks information. Exemple: Fuel: 2014-01-01 at 1000 km Fuel:
>>> 2014-01-11 at 2000 km
>>>
>>> If new cost import at 2014-01-06, we can use 1500km as distance.
>>> If new cost is newer than all fuel, we can take the last distance
>>> information.
>>>
>>> I will commit this release today (and generate a new version), and
>>> probably work on this feature tomorrow... to generate it next week.
>>>
>>> Another feature I want to do is to sort station and fueltype by usage,
>>> ie by total quantity of fuel use by this type or station...
>>>
>>> --
>>> Reply to this email directly or view it on GitHub[1].
>>>
>>
>> Links:
>> ------
>> [1] https://github.com/condo4/carbudget/pull/10#issuecomment-83613984
>>
>> --
>> Reply to this email directly or view it on GitHub [1].
>
> Links:
> ------
> [1] https://github.com/condo4/carbudget/pull/10#issuecomment-83615645
>
>   —
> Reply to this email directly or view it on GitHub[1].
>       



Links:
------
[1] https://github.com/condo4/carbudget/pull/10#issuecomment-83616601

**Comment by condo4** [comment]
Hello,

Your patch to add MyCar import is refuse by Jolla harbour QA validation.
I fixed a first problem in the yaml file for rpm (add depends to qt5-qtdeclarative-import-xmllistmodel)
But you need avoid the hard coded path for the xml file:


Sandboxing
==========
ERROR [/usr/share/harbour-carbudget/qml/pages/MyCarImportMainview.qml] Hardcoded path: source: "/home/nemo/mycar_data.xml"
INFO [/usr/share/harbour-carbudget/qml/pages/MyCarImportMainview.qml] Please do not hard code the path to any subfolders in /home/nemo. As a rule of thumb follow the XDG Base Directory Specification and use $HOME instead of /home/nemo.
INFO [/usr/share/harbour-carbudget/qml/pages/MyCarImportMainview.qml] Please see our FAQ here: https://harbour.jolla.com/faq#2.13.0
ERROR [/usr/bin/harbour-carbudget] Hardcoded path: /home/nemo/mycar_data.xml

Here is information how you can validate your RPM with SailfishSDK: https://harbour.jolla.com/faq#9.1.0


I think you can just list all file "$HOME/*.xml" in a ListView and just select the file we want to import...

**Comment by thmichel** [comment]
Hi Fabien,

ok, need to look into that. From what I read it may be enough to replace
/home/nemo with $HOME, but the cleaner solution would be a selectable file.

I will try to add that in. Not sure when I can finish that; so if you want
to publish a new version it might be easier to leave the import support out
or go for the workaround using $HOME.

I think I can do the file selection by the end of this week.

Regards,

Tom.

Zitat von Proriol Fabien <notifications@github.com>:

> Hello,
>
>   Your patch to add MyCar import is refuse by Jolla harbour QA
validation.
> I fixed a first problem in the yaml file for rpm (add depends to
> qt5-qtdeclarative-import-xmllistmodel)
> But you need avoid the hard coded path for the xml file:
>
>   SANDBOXING
>
>   ERROR [/usr/share/harbour-carbudget/qml/pages/MyCarImportMainview.qml]
> Hardcoded path: source: "/home/nemo/mycar_data.xml"
> INFO [/usr/share/harbour-carbudget/qml/pages/MyCarImportMainview.qml]
> Please do not hard code the path to any subfolders in /home/nemo. As a
> rule of thumb follow the XDG Base Directory Specification and use $HOME
> instead of /home/nemo.
> INFO [/usr/share/harbour-carbudget/qml/pages/MyCarImportMainview.qml]
> Please see our FAQ here: https://harbour.jolla.com/faq#2.13.0
> ERROR [/usr/bin/harbour-carbudget] Hardcoded path:
> /home/nemo/mycar_data.xml
>
>   Here is information how you can validate your RPM with SailfishSDK:
> https://harbour.jolla.com/faq#9.1.0
>
>   I think you can just list all file "$HOME/*.xml" in a ListView and
> just select the file we want to import...
>
>   —
> Reply to this email directly or view it on GitHub[1].
>       



Links:
------
[1] https://github.com/condo4/carbudget/pull/10#issuecomment-85996328

**Comment by thmichel** [comment]
Hi Fabien,

it was easier as I thought, I added a file dialog showing all files in the
home directory. Validaiotn in the SDK only showed one error - vendor not
set.

I create a pull request now.

Regards,

Tom.

Zitat von Proriol Fabien <notifications@github.com>:

> Hello,
>
>   Your patch to add MyCar import is refuse by Jolla harbour QA
validation.
> I fixed a first problem in the yaml file for rpm (add depends to
> qt5-qtdeclarative-import-xmllistmodel)
> But you need avoid the hard coded path for the xml file:
>
>   SANDBOXING
>
>   ERROR [/usr/share/harbour-carbudget/qml/pages/MyCarImportMainview.qml]
> Hardcoded path: source: "/home/nemo/mycar_data.xml"
> INFO [/usr/share/harbour-carbudget/qml/pages/MyCarImportMainview.qml]
> Please do not hard code the path to any subfolders in /home/nemo. As a
> rule of thumb follow the XDG Base Directory Specification and use $HOME
> instead of /home/nemo.
> INFO [/usr/share/harbour-carbudget/qml/pages/MyCarImportMainview.qml]
> Please see our FAQ here: https://harbour.jolla.com/faq#2.13.0
> ERROR [/usr/bin/harbour-carbudget] Hardcoded path:
> /home/nemo/mycar_data.xml
>
>   Here is information how you can validate your RPM with SailfishSDK:
> https://harbour.jolla.com/faq#9.1.0
>
>   I think you can just list all file "$HOME/*.xml" in a ListView and
> just select the file we want to import...
>
>   —
> Reply to this email directly or view it on GitHub[1].
>       



Links:
------
[1] https://github.com/condo4/carbudget/pull/10#issuecomment-85996328

**Comment by thmichel** [comment]
Hi,

if you send me a backup file of your old application, I could look into it
(at leas if I understand the format, is it xml?).

Regards,

Tom.

Zitat von Proriol Fabien <notifications@github.com>:

> Hi,
>
> I think also it will be greate to select the xml file from a list
> instead of a hard coded name, for exemple, we can propose all ~/*.xml
> and ~/Documents/*.xml
>
> I want to write also the import from the old N900 application I used,
> but, at this time, I hadn't the time to do it...
>
> Fabien
>
>> Hi,
>>
>> that's great.
>>
>> I already found some bugs in the code I worte and did some more changes
>> (mainly to the statistics and some gui modifications)
>>
>> I'll merge your changes into mine and send another pull request later
on.
>>
>> Regarding the simulations: I was just too lazy to rewrite all the
>> statements :-) I have an xml Export from myCar with about 100 fuel
>> records
>> and some 20 costs that I use for testing...
>>
>> Thanks for merging my changes!
>>
>> Zitat von Proriol Fabien <notifications@github.com>:
>>
>>> I rewrite your patch, because, there is some bug when I test all
>>> features, it was missing simulation (I use this to check if all is
>>> working well), and I need to separate this 3 features:
>>>
>>>
>>> * FuelType
>>> * CostType
>>> * Import Today, I merged FuelType and CostType, but I need to work
>>> a lot for Import... In fact, in my apps, I really need a distance for
>>> cost, because I will use it to do some statistics. In your case, I
think
>>> the good way is to calculate by a lineare interpolation the distance
>>> with fuel tanks information. Exemple: Fuel: 2014-01-01 at 1000 km Fuel:
>>> 2014-01-11 at 2000 km
>>>
>>> If new cost import at 2014-01-06, we can use 1500km as distance.
>>> If new cost is newer than all fuel, we can take the last distance
>>> information.
>>>
>>> I will commit this release today (and generate a new version), and
>>> probably work on this feature tomorrow... to generate it next week.
>>>
>>> Another feature I want to do is to sort station and fueltype by usage,
>>> ie by total quantity of fuel use by this type or station...
>>>
>>> --
>>> Reply to this email directly or view it on GitHub[1].
>>>
>>
>> Links:
>> ------
>> [1] https://github.com/condo4/carbudget/pull/10#issuecomment-83613984
>>
>> --
>> Reply to this email directly or view it on GitHub [1].
>
> Links:
> ------
> [1] https://github.com/condo4/carbudget/pull/10#issuecomment-83615645
>
>   —
> Reply to this email directly or view it on GitHub[1].
>       



Links:
------
[1] https://github.com/condo4/carbudget/pull/10#issuecomment-83616601

**Comment by condo4** [comment]
I put an FuelPad file on:
http://saint-pal.kazoe.org/20110531_fuelpad.db
This is SQLite 3.x database format...

**Comment by thmichel** [comment]
Zitat von Proriol Fabien <notifications@github.com>:

> I put an FuelPad file on:
> http://saint-pal.kazoe.org/20110531_fuelpad.db
> This is SQLite 3.x database format...
>
>   —
> Reply to this email directly or view it on GitHub[1].
>       

Hi,

I've created a first basic import feature. It currently imports only tanks,
adding costs will not be too difficult. I will work on that tomorrow.

I renamed "Import from myCar" to "Import car" and show a list of xml and db
files in the home directory (will rework this later to allow subdirectories
as well). Depending on the file type either mycar of fuelpad import is
called.

I'll create an initial pull request so you can have a look at the
implementation.

Regards,

Tom.

Links:
------
[1] https://github.com/condo4/carbudget/pull/10#issuecomment-86100170

**Comment by thmichel** [comment]
Zitat von Proriol Fabien <notifications@github.com>:

> I put an FuelPad file on:
> http://saint-pal.kazoe.org/20110531_fuelpad.db
> This is SQLite 3.x database format...
>
>   —
> Reply to this email directly or view it on GitHub[1].
>       

Hi Fabien,

I've finished the import for the FuelPad database so far (I think I import
all items that can be imported, as CarBudget does not have all items like
alarms).

It seems I can't create a new pull request as my old one is still open.
Once you have accepted that, I create the new one.

I saw that in Fuelpad you could enter some more car properties like Vendor
etc. If you want my to add that to CarBudget, just give me a note.

I received my Jolla phone last week and I am very happy I can continue
logging my car expenses with a native app, thanks a lot for that!

Regards,

Tom.


Links:
------
[1] https://github.com/condo4/carbudget/pull/10#issuecomment-86100170

**Comment by condo4** [comment]
I merged your change for 0.11 (submited for aprouval today)
I just changed tire view navigation to avoid to change too much the navigation for users...
I notice also many warning in the statistics view because it is forbidden to use top and bottom anchors in a Row... I add Rectangle to add MouseArea.

**Comment by thmichel** [comment]
Hi,

great, thanks. Now that you mention it I noticed the warnings too...

My idea with the tire mount navigation was to make it similar to the costs
and tanks - clicking on the icon shows the history, clicking on the button
allows you to add new items.

But I am happy with your solution too :-)

I saw that you can add costs for tires when creating a new set of tires, I
will add that to the statistics.

Regards,

Thomas.

Zitat von Proriol Fabien <notifications@github.com>:

> I merged your change for 0.11 (submited for aprouval today)
> I just changed tire view navigation to avoid to change too much the
> navigation for users...
> I notice also many warning in the statistics view because it is
> forbidden to use top and bottom anchors in a Row... I add Rectangle to
> add MouseArea.
>
>   —
> Reply to this email directly or view it on GitHub[1].
>       



Links:
------
[1] https://github.com/condo4/carbudget/pull/10#issuecomment-92909093

**Pull request merged**
