### PR TITLE
MyBackup and Sailjail support

### LINKED ISSUE #77: Add Sailjail configuration
Add minimal required Sailjail permissions to the .desktop file.

(Consider this bug assigned to me.)

### PR DESCRIPTION
**Pull request by direc85**
Adds support for Sailfish OS built-in backup via MyBackup, and adds minimal Sailjail configuration: only user directories and memory card access is needed for import/export functionality.

Fixes #77 and #78

### CODE REVIEW

**Comment by direc85** [comment]
MyBackup integration is tested by making an actual backup and checking the contents.

Sailjail config is tested by opening and changing cars, making backups and importing them.

**Comment by condo4** [comment]
I merged all pull request, I don't have any Jolla phone to test now, can you test if the master is ok, I will try to reinstall sdk and generate a new release next week

**Comment by direc85** [comment]
I've been poking around the master build and it seems to work fine. The missed tank feature seems to also work after a quick 5-minute test. LGTM for a new release! It's been a while since the prevous one ;)... I can also send you the RPMs if you run into issues installing the SDK or compiling the application.

**Comment by condo4** [comment]
Hello, I plan to build a new release in 10 days, don't hesitate to test before, and if you have some others pull request...

**Comment by condo4** [comment]
A bit late, but my fiber optic line is broken since 1 month....
So I don't have anymore internet currently.
Waiting for repare, I hope this will occure before the end of this month...

**Comment by condo4** [comment]
Still late, I have difficulties to have a working Sailfish OS sdk on my PC (linux)...

**Pull request merged**
