### PR TITLE
Enhanced statistics

### PR DESCRIPTION
**Pull request by thmichel**
- Enabled drilldown of statistics
- Added Pie charts to statistics
- some reworks of costlist and tanklist views to allow filtering for statistics drilldown
- updates for German translations

### CODE REVIEW

**Comment by thmichel** [comment]
Zitat von Proriol Fabien <notifications@github.com>:

> Merged #16[1].
>
>   —
> Reply to this email directly or view it on GitHub[2].
>       

Hi Fabriol,

thanks for that.

There are some other topics that came into my mind during coding:

Would it make sense to add a field for buying price to the car class? This
would help in the statistics as you may want to leave that out of the
calculation for running costs (or show it as a seperate item).

The concept of tires is not yet clear to me. When replacing a single tire /
two tires only due to a tire fault, how would we handle that in the
calculation? Also, how to unmount/mount them as they are now just a "half"
tire set?

And last (though not a high prio for me), would it make sense to add
something like income? E.g. your company pas you for a drive or you sell
the car.

Regards,

Tom.



Links:
------
[1] https://github.com/condo4/carbudget/pull/16
[2] https://github.com/condo4/carbudget/pull/16#event-289338422

**Comment by condo4** [comment]
À ven. avr. 24 16:59:54 2015 GMT+0200, thmichel a écrit :
>   Zitat von Proriol Fabien <notifications@github.com>:
> 
> > Merged #16[1].
> >
> >   —
> > Reply to this email directly or view it on GitHub[2].
> >       
> 
> Hi Fabriol,
> 
> thanks for that.
> 
> There are some other topics that came into my mind during coding:
> 
> Would it make sense to add a field for buying price to the car class? This
> would help in the statistics as you may want to leave that out of the
> calculation for running costs (or show it as a seperate item).


Yes it can make sense, I went to add it, but how to know the number of km the car can do to estimate the cost by km ?...


 
> The concept of tires is not yet clear to me. When replacing a single tire /
> two tires only due to a tire fault, how would we handle that in the
> calculation? Also, how to unmount/mount them as they are now just a "half"
> tire set?
The concept is, for exemple, if you have tire for winter, and other for summer, at the end of winter, you umount winter tire and mount summer tire.
If winter tire was dead, you check "trash" check box.
Else, you can re-mount the next winter.
When a tire set is dead, we can calculate the cost by km...
I want to find a way to estimate the cost early, but I have no idea to do them.
For tire fault, I don't think a way yet...
In fact I coded this application when I have a need for my car...
My job don't leave me many time to work on it...
Thanks to your implication, you improve it more than me this year... 


> 
> And last (though not a high prio for me), would it make sense to add
> something like income? E.g. your company pas you for a drive or you sell
> the car.
Why not :-)
I also start to think a way to synchronize data to the futur tablet...
By bluetooth, or by a third cloud server and an account...
 
Regards,
Fabien
> 
> 
> 
> Links:
> ------
> [1] https://github.com/condo4/carbudget/pull/16
> [2] https://github.com/condo4/carbudget/pull/16#event-289338422
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/condo4/carbudget/pull/16#issuecomment-9595619

-- 
Envoyé depuis mon Jolla

**Comment by thmichel** [comment]
Hi Fabiol,

thanks for your answer.

The idea with the buying price was that one can have a price/100km in the
statistic with just the running costs. One could think of additional field
in the car like "Estimated usage" and "Estimated selling value" as well,
which might be usefull for leasing cars. If you don't mind, I will modify
the car class accordingly.

I understand the Winter/Summer tire concept, my question was just how to
work with uncomplete tire sets (for example, some peaple just change tires
on one axle).
An option would be instead of retirement of a whole tire set allow just
some tires to expire or give a dedicated number in a tireset and allow
mounting of multiple tireset if the have less tires then the car. But
that's all a bit complex so maybe we should keep it that way for now.

Sync with the tablet would be great, though I have no idea yet how to do
that...

Regards,

Tom.

Zitat von Proriol Fabien <notifications@github.com>:

> À ven. avr. 24 16:59:54 2015 GMT+0200, thmichel a écrit :
>> Zitat von Proriol Fabien <notifications@github.com>:
>>
>> > Merged #16[1].
>> >
>> > —
>> > Reply to this email directly or view it on GitHub[2].
>> >
>>
>> Hi Fabriol,
>>
>> thanks for that.
>>
>> There are some other topics that came into my mind during coding:
>>
>> Would it make sense to add a field for buying price to the car class?
>> This
>> would help in the statistics as you may want to leave that out of the
>> calculation for running costs (or show it as a seperate item).
>
> Yes it can make sense, I went to add it, but how to know the number of
> km the car can do to estimate the cost by km ?...
>
>> The concept of tires is not yet clear to me. When replacing a single
>> tire /
>> two tires only due to a tire fault, how would we handle that in the
>> calculation? Also, how to unmount/mount them as they are now just a
>> "half"
>> tire set?
> The concept is, for exemple, if you have tire for winter, and other for
> summer, at the end of winter, you umount winter tire and mount summer
> tire.
> If winter tire was dead, you check "trash" check box.
> Else, you can re-mount the next winter.
> When a tire set is dead, we can calculate the cost by km...
> I want to find a way to estimate the cost early, but I have no idea to
> do them.
> For tire fault, I don't think a way yet...
> In fact I coded this application when I have a need for my car...
> My job don't leave me many time to work on it...
> Thanks to your implication, you improve it more than me this year...
>
>>
>> And last (though not a high prio for me), would it make sense to add
>> something like income? E.g. your company pas you for a drive or you sell
>> the car.
> Why not :-)
> I also start to think a way to synchronize data to the futur tablet...
> By bluetooth, or by a third cloud server and an account...
>
> Regards,
> Fabien
>>
>>
>>
>> Links:
>> ------
>> [1] https://github.com/condo4/carbudget/pull/16
>> [2] https://github.com/condo4/carbudget/pull/16#event-289338422
>>
>>
>> ---
>> Reply to this email directly or view it on GitHub:
>> https://github.com/condo4/carbudget/pull/16#issuecomment-9595619
>
> --
> Envoyé depuis mon Jolla
>   —
> Reply to this email directly or view it on GitHub[1].
>       



Links:
------
[1] https://github.com/condo4/carbudget/pull/16#issuecomment-96231155

**Comment by condo4** [comment]
Le 2015-04-30 09:41, thmichel a écrit : 

> Hi Fabiol,
> 
> thanks for your answer.
> 
> The idea with the buying price was that one can have a price/100km in the
> statistic with just the running costs. One could think of additional field
> in the car like "Estimated usage" and "Estimated selling value" as well,
> which might be usefull for leasing cars. If you don't mind, I will modify
> the car class accordingly.

Yes, it can be a solution to add a field for estimated usage... 

> I understand the Winter/Summer tire concept, my question was just how to
> work with uncomplete tire sets (for example, some peaple just change tires
> on one axle).

In fact, If this people change tire 2 by 2, it is possible to mount 2
set of 2 tires... 

And change only one set... (for example, people who change only front
tire for winter). 

I'm not very glad on my solution... 

Perhaps a picture of the car with a clickable wheel and button to change
all/only front/only rear in 1 action can be better... 

The think I unlike in the current interface, is, if we want to change
wheels, we need 2 actions ( umount + mount) and enter 2 times the ODO
field... 

This part of this application can be improve, I think... 

In order to test different solutions, it can be possible to create a git
branch to avoid too many change on the "stable" release, the time we
find a best solution... 

I think in few month, I will have more time to work on it... 

This month (and since beginning of this year), I have too much work to
work on this application... 

> An option would be instead of retirement of a whole tire set allow just 
> 
> some tires to expire or give a dedicated number in a tireset and allow
> mounting of multiple tireset if the have less tires then the car. But
> that's all a bit complex so maybe we should keep it that way for now.
> 
> Sync with the tablet would be great, though I have no idea yet how to do
> that...

I have some ideas... with a cloud server... but, this solution need to
share datas with my server... 

It can be an optional feature, with a page to set account
login/password... 

I will think about this solution... 

Regards, and thanks for all the work you do on this application !!! 

Fabien 

> Regards,
> 
> Tom.
> 
> Zitat von Proriol Fabien <notifications@github.com>:
> 
>> À ven. avr. 24 16:59:54 2015 GMT+0200, thmichel a écrit :
>>> Zitat von Proriol Fabien <notifications@github.com>:
>>>
>>> > Merged #16[1].
>>> >
>>> > --
>>> > Reply to this email directly or view it on GitHub[2].
>>> >
>>>
>>> Hi Fabriol,
>>>
>>> thanks for that.
>>>
>>> There are some other topics that came into my mind during coding:
>>>
>>> Would it make sense to add a field for buying price to the car class?
>>> This
>>> would help in the statistics as you may want to leave that out of the
>>> calculation for running costs (or show it as a seperate item).
>>
>> Yes it can make sense, I went to add it, but how to know the number of
>> km the car can do to estimate the cost by km ?...
>>
>>> The concept of tires is not yet clear to me. When replacing a single
>>> tire /
>>> two tires only due to a tire fault, how would we handle that in the
>>> calculation? Also, how to unmount/mount them as they are now just a
>>> "half"
>>> tire set?
>> The concept is, for exemple, if you have tire for winter, and other for
>> summer, at the end of winter, you umount winter tire and mount summer
>> tire.
>> If winter tire was dead, you check "trash" check box.
>> Else, you can re-mount the next winter.
>> When a tire set is dead, we can calculate the cost by km...
>> I want to find a way to estimate the cost early, but I have no idea to
>> do them.
>> For tire fault, I don't think a way yet...
>> In fact I coded this application when I have a need for my car...
>> My job don't leave me many time to work on it...
>> Thanks to your implication, you improve it more than me this year...
>>
>>>
>>> And last (though not a high prio for me), would it make sense to add
>>> something like income? E.g. your company pas you for a drive or you sell
>>> the car.
>> Why not :-)
>> I also start to think a way to synchronize data to the futur tablet...
>> By bluetooth, or by a third cloud server and an account...
>>
>> Regards,
>> Fabien
>>>
>>>
>>>
>>> Links:
>>> ------
>>> [1] https://github.com/condo4/carbudget/pull/16
>>> [2] https://github.com/condo4/carbudget/pull/16#event-289338422
>>>
>>>
>>> ---
>>> Reply to this email directly or view it on GitHub:
>>> https://github.com/condo4/carbudget/pull/16#issuecomment-9595619
>>
>> --
>> Envoyé depuis mon Jolla
>> --
>> Reply to this email directly or view it on GitHub[1].
>> 
> 
> Links:
> ------
> [1] https://github.com/condo4/carbudget/pull/16#issuecomment-96231155 
> 
> --
> Reply to this email directly or view it on GitHub [1].

 

Links:
------
[1] https://github.com/condo4/carbudget/pull/16#issuecomment-97695316

**Comment by thmichel** [comment]
Hi,
I've implemented a first version to implement buyng costs. The idea is as
follows:

- The user can enter the buying costs, estimated selling value and
estimated lifetime in months
- if lifetime is set to 0, cost per 100KM are calculated as (buying price -
selling price) / KM *100
- if an estimated lifetime iss given, the costs are calculated as ((buying
price - selling price)/lifetime)*current usage time) /KM * 100

The idea is to have a realistic cost/100 KM from the beginning - if you by
a car for 20.000 Euro you would have costs of more than 200 Euro/100 KM
shown in the statistic if you just drove 100 KM with the car.

So in the statistics you can distinguish between all running costs (fuel,
tires, costs) and the investment cost (buying/selling price).

I have not yet created a pull request, if you think this makes sense, I
will do (you can have a look at the code on my git repo).

Regarding tires: I agree, a new branch would make sense here as this
requires some experimenting.

Regards,

Tom.

**Comment by condo4** [comment]
Hi, 

I think this make sense; I probably generate a new version with all your
change next week... If we add time to test and fix some bugs... 

In statistics, there is a strange things, if we scroll the page, the
graphic don't move, and text is under the graphic... 

In a first time for tires, we can also use the same idea... if the tire
is trashed, we calculate the real cost by km, else, we use the estimated
lifetime (enter in km, and calculate month price with average of
km/month)... It can be a "quick" solution before a complete one with the
futur interface... 

I push a new branch (tire_experimentation) for the new interface work...


Fabien 

> Hi,
> I've implemented a first version to implement buyng costs. The idea is as
> follows:
> 
> - The user can enter the buying costs, estimated selling value and
> estimated lifetime in months
> - if lifetime is set to 0, cost per 100KM are calculated as (buying price -
> selling price) / KM *100
> - if an estimated lifetime iss given, the costs are calculated as ((buying
> price - selling price)/lifetime)*current usage time) /KM * 100
> 
> The idea is to have a realistic cost/100 KM from the beginning - if you by
> a car for 20.000 Euro you would have costs of more than 200 Euro/100 KM
> shown in the statistic if you just drove 100 KM with the car.
> 
> So in the statistics you can distinguish between all running costs (fuel,
> tires, costs) and the investment cost (buying/selling price).
> 
> I have not yet created a pull request, if you think this makes sense, I
> will do (you can have a look at the code on my git repo).
> 
> Regarding tires: I agree, a new branch would make sense here as this
> requires some experimenting.
> 
> Regards,
> 
> Tom. 
> 
> --
> Reply to this email directly or view it on GitHub [1].

 

Links:
------
[1] https://github.com/condo4/carbudget/pull/16#issuecomment-98856010

**Comment by thmichel** [comment]
Hi,

thegraphic isn't moving by intention :-)

The idea was to have only the list scrolling so you could still see the
graphic when at the bottom of the list. The only problem is the text
scrolls into the graphic.

I look into that and try to fix it before creating the pull request.

Zitat von Proriol Fabien <notifications@github.com>:

> Hi,
>
> I think this make sense; I probably generate a new version with all your
> change next week... If we add time to test and fix some bugs...
>
> In statistics, there is a strange things, if we scroll the page, the
> graphic don't move, and text is under the graphic...
>
> In a first time for tires, we can also use the same idea... if the tire
> is trashed, we calculate the real cost by km, else, we use the estimated
> lifetime (enter in km, and calculate month price with average of
> km/month)... It can be a "quick" solution before a complete one with the
> futur interface...
>
> I push a new branch (tire_experimentation) for the new interface work...
>
> Fabien
>
>> Hi,
>> I've implemented a first version to implement buyng costs. The idea is
as
>> follows:
>>
>> - The user can enter the buying costs, estimated selling value and
>> estimated lifetime in months
>> - if lifetime is set to 0, cost per 100KM are calculated as (buying
>> price -
>> selling price) / KM *100
>> - if an estimated lifetime iss given, the costs are calculated as
>> ((buying
>> price - selling price)/lifetime)*current usage time) /KM * 100
>>
>> The idea is to have a realistic cost/100 KM from the beginning - if you
>> by
>> a car for 20.000 Euro you would have costs of more than 200 Euro/100 KM
>> shown in the statistic if you just drove 100 KM with the car.
>>
>> So in the statistics you can distinguish between all running costs
(fuel,
>> tires, costs) and the investment cost (buying/selling price).
>>
>> I have not yet created a pull request, if you think this makes sense, I
>> will do (you can have a look at the code on my git repo).
>>
>> Regarding tires: I agree, a new branch would make sense here as this
>> requires some experimenting.
>>
>> Regards,
>>
>> Tom.
>>
>> --
>> Reply to this email directly or view it on GitHub [1].
>
> Links:
> ------
> [1] https://github.com/condo4/carbudget/pull/16#issuecomment-98856010
>
>   —
> Reply to this email directly or view it on GitHub[1].
>       



Links:
------
[1] https://github.com/condo4/carbudget/pull/16#issuecomment-99031695

**Comment by thmichel** [comment]
Hi,

I finally finished the statistics / investment stuff and created a pull
request. I will now start working on the tire stuff (as soon as I found out
how to work with branches :-) )

Regards,

Tom.

Zitat von Proriol Fabien <notifications@github.com>:

> Hi,
>
> I think this make sense; I probably generate a new version with all your
> change next week... If we add time to test and fix some bugs...
>
> In statistics, there is a strange things, if we scroll the page, the
> graphic don't move, and text is under the graphic...
>
> In a first time for tires, we can also use the same idea... if the tire
> is trashed, we calculate the real cost by km, else, we use the estimated
> lifetime (enter in km, and calculate month price with average of
> km/month)... It can be a "quick" solution before a complete one with the
> futur interface...
>
> I push a new branch (tire_experimentation) for the new interface work...
>
> Fabien
>
>> Hi,
>> I've implemented a first version to implement buyng costs. The idea is
as
>> follows:
>>
>> - The user can enter the buying costs, estimated selling value and
>> estimated lifetime in months
>> - if lifetime is set to 0, cost per 100KM are calculated as (buying
>> price -
>> selling price) / KM *100
>> - if an estimated lifetime iss given, the costs are calculated as
>> ((buying
>> price - selling price)/lifetime)*current usage time) /KM * 100
>>
>> The idea is to have a realistic cost/100 KM from the beginning - if you
>> by
>> a car for 20.000 Euro you would have costs of more than 200 Euro/100 KM
>> shown in the statistic if you just drove 100 KM with the car.
>>
>> So in the statistics you can distinguish between all running costs
(fuel,
>> tires, costs) and the investment cost (buying/selling price).
>>
>> I have not yet created a pull request, if you think this makes sense, I
>> will do (you can have a look at the code on my git repo).
>>
>> Regarding tires: I agree, a new branch would make sense here as this
>> requires some experimenting.
>>
>> Regards,
>>
>> Tom.
>>
>> --
>> Reply to this email directly or view it on GitHub [1].
>
> Links:
> ------
> [1] https://github.com/condo4/carbudget/pull/16#issuecomment-98856010
>
>   —
> Reply to this email directly or view it on GitHub[1].
>       



Links:
------
[1] https://github.com/condo4/carbudget/pull/16#issuecomment-99031695

**Pull request merged**
